# Generated by Django 5.1.7 on 2025-03-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('session_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('message_id', models.BigIntegerField()),
                ('message_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='telegram_ch_session_c2cfef_idx')],
                'unique_together': {('session_id', 'contact', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('session_id', models.CharField(max_length=36)),
                ('dialog_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_message', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('unread_count', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='telegram.contact')),
            ],
            options={
                'unique_together': {('session_id', 'contact', 'dialog_id')},
            },
        ),
    ]
