# Generated by Django 5.1.7 on 2025-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='media_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
